// src/main/webapp/app/entities/supply-point/supply-point.tsx
import React, { useState, useEffect } from 'react';
import InfiniteScroll from 'react-infinite-scroller';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, getSortState, IPaginationBaseState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities, reset } from './supply-point.reducer';
import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface ISupplyPointProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const SupplyPoint = (props: ISupplyPointProps) => {
  const [search, setSearch] = useState('');
  const [paginationState, setPaginationState] = useState(getSortState(props.location, ITEMS_PER_PAGE));
  const [sorting, setSorting] = useState(false);

  const getAllEntities = () => {
    if (search) {
      props.getSearchEntities(
        search,
        paginationState.activePage - 1,
        paginationState.itemsPerPage,
        `${paginationState.sort},${paginationState.order}`
      );
    } else {
      props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
    }
  };

  const resetAll = () => {
    props.reset();
    setPaginationState({
      ...paginationState,
      activePage: 1
    });
  };

  useEffect(() => {
    resetAll();
  }, []);

  const startSearching = () => {
    if (search) {
      props.reset();
      setPaginationState({
        ...paginationState,
        activePage: 1
      });
      props.getSearchEntities(
        search,
        paginationState.activePage - 1,
        paginationState.itemsPerPage,
        `${paginationState.sort},${paginationState.order}`
      );
    }
  };

  const clear = () => {
    props.reset();
    setSearch('');
    setPaginationState({
      ...paginationState,
      activePage: 1
    });
    props.getEntities();
  };

  const handleSearch = event => setSearch(event.target.value);

  useEffect(() => {
    getAllEntities();
  }, [paginationState.activePage]);

  const handleLoadMore = () => {
    if (window.pageYOffset > 0) {
      setPaginationState({
        ...paginationState,
        activePage: paginationState.activePage + 1
      });
    }
  };

  useEffect(() => {
    if (sorting) {
      getAllEntities();
      setSorting(false);
    }
  }, [sorting, search]);

  const sort = p => () => {
    props.reset();
    setPaginationState({
      ...paginationState,
      activePage: 1,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p
    });
    setSorting(true);
  };

  const { supplyPointList, match, loading } = props;
  return (
    <div>
      <h2 id="supply-point-heading">
        <Translate contentKey="crownApp.supplyPoint.home.title">Supply Points</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="crownApp.supplyPoint.home.createLabel">Create new Supply Point</Translate>
        </Link>
      </h2>
      <Row>
        <Col sm="12">
          <AvForm onSubmit={startSearching}>
            <AvGroup>
              <InputGroup>
                <AvInput
                  type="text"
                  name="search"
                  value={search}
                  onChange={handleSearch}
                  placeholder={translate('crownApp.supplyPoint.home.search')}
                />
                <Button className="input-group-addon">
                  <FontAwesomeIcon icon="search" />
                </Button>
                <Button type="reset" className="input-group-addon" onClick={clear}>
                  <FontAwesomeIcon icon="trash" />
                </Button>
              </InputGroup>
            </AvGroup>
          </AvForm>
        </Col>
      </Row>
      <div className="table-responsive">
        <InfiniteScroll
          pageStart={paginationState.activePage}
          loadMore={handleLoadMore}
          hasMore={paginationState.activePage - 1 < props.links.next}
          loader={<div className="loader">Loading ...</div>}
          threshold={0}
          initialLoad={false}
        >
          {supplyPointList && supplyPointList.length > 0 ? (
            <Table responsive>
              <thead>
                <tr>
                  <th className="hand" onClick={sort('id')}>
                    <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('name')}>
                    <Translate contentKey="crownApp.supplyPoint.name">Name</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('address')}>
                    <Translate contentKey="crownApp.supplyPoint.address">Address</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('primaryContactName')}>
                    <Translate contentKey="crownApp.supplyPoint.primaryContactName">Primary Contact Name</Translate>{' '}
                    <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('zip')}>
                    <Translate contentKey="crownApp.supplyPoint.zip">Zip</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('phonenumber')}>
                    <Translate contentKey="crownApp.supplyPoint.phonenumber">Phonenumber</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('latx')}>
                    <Translate contentKey="crownApp.supplyPoint.latx">Latx</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('longy')}>
                    <Translate contentKey="crownApp.supplyPoint.longy">Longy</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('city')}>
                    <Translate contentKey="crownApp.supplyPoint.city">City</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('state')}>
                    <Translate contentKey="crownApp.supplyPoint.state">State</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('isDistributor')}>
                    <Translate contentKey="crownApp.supplyPoint.isDistributor">Is Distributor</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('isHealthcare')}>
                    <Translate contentKey="crownApp.supplyPoint.isHealthcare">Is Healthcare</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('hasSterilization')}>
                    <Translate contentKey="crownApp.supplyPoint.hasSterilization">Has Sterilization</Translate>{' '}
                    <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('priority')}>
                    <Translate contentKey="crownApp.supplyPoint.priority">Priority</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('notes')}>
                    <Translate contentKey="crownApp.supplyPoint.notes">Notes</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {supplyPointList.map((supplyPoint, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${supplyPoint.id}`} color="link" size="sm">
                        {supplyPoint.id}
                      </Button>
                    </td>
                    <td>{supplyPoint.name}</td>
                    <td>{supplyPoint.address}</td>
                    <td>{supplyPoint.primaryContactName}</td>
                    <td>{supplyPoint.zip}</td>
                    <td>{supplyPoint.phonenumber}</td>
                    <td>{supplyPoint.latx}</td>
                    <td>{supplyPoint.longy}</td>
                    <td>{supplyPoint.city}</td>
                    <td>{supplyPoint.state}</td>
                    <td>{supplyPoint.isDistributor ? 'true' : 'false'}</td>
                    <td>{supplyPoint.isHealthcare ? 'true' : 'false'}</td>
                    <td>{supplyPoint.hasSterilization ? 'true' : 'false'}</td>
                    <td>{supplyPoint.priority}</td>
                    <td>{supplyPoint.notes}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${supplyPoint.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${supplyPoint.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${supplyPoint.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            !loading && (
              <div className="alert alert-warning">
                <Translate contentKey="crownApp.supplyPoint.home.notFound">No Supply Points found</Translate>
              </div>
            )
          )}
        </InfiniteScroll>
      </div>
    </div>
  );
};

const mapStateToProps = ({ supplyPoint }: IRootState) => ({
  supplyPointList: supplyPoint.entities,
  loading: supplyPoint.loading,
  totalItems: supplyPoint.totalItems,
  links: supplyPoint.links,
  entity: supplyPoint.entity,
  updateSuccess: supplyPoint.updateSuccess
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPoint);

// src/main/webapp/app/entities/supply-point/supply-point.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiParseLinks } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ISupplyPoint } from 'app/shared/model/supply-point.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { SupplyPointService } from './supply-point.service';
import { SupplyPointDeleteDialogComponent } from './supply-point-delete-dialog.component';

@Component({
  selector: 'jhi-supply-point',
  templateUrl: './supply-point.component.html'
})
export class SupplyPointComponent implements OnInit, OnDestroy {
  supplyPoints: ISupplyPoint[];
  eventSubscriber?: Subscription;
  itemsPerPage: number;
  links: any;
  page: number;
  predicate: string;
  ascending: boolean;
  currentSearch: string;

  constructor(
    protected supplyPointService: SupplyPointService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal,
    protected parseLinks: JhiParseLinks,
    protected activatedRoute: ActivatedRoute
  ) {
    this.supplyPoints = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0
    };
    this.predicate = 'id';
    this.ascending = true;
    this.currentSearch =
      this.activatedRoute.snapshot && this.activatedRoute.snapshot.queryParams['search']
        ? this.activatedRoute.snapshot.queryParams['search']
        : '';
  }

  loadAll(): void {
    if (this.currentSearch) {
      this.supplyPointService
        .search({
          query: this.currentSearch,
          page: this.page,
          size: this.itemsPerPage,
          sort: this.sort()
        })
        .subscribe((res: HttpResponse<ISupplyPoint[]>) => this.paginateSupplyPoints(res.body, res.headers));
      return;
    }

    this.supplyPointService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe((res: HttpResponse<ISupplyPoint[]>) => this.paginateSupplyPoints(res.body, res.headers));
  }

  reset(): void {
    this.page = 0;
    this.supplyPoints = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  search(query: string): void {
    this.supplyPoints = [];
    this.links = {
      last: 0
    };
    this.page = 0;
    if (query) {
      this.predicate = '_score';
      this.ascending = false;
    } else {
      this.predicate = 'id';
      this.ascending = true;
    }
    this.currentSearch = query;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInSupplyPoints();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: ISupplyPoint): string {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInSupplyPoints(): void {
    this.eventSubscriber = this.eventManager.subscribe('supplyPointListModification', () => this.reset());
  }

  delete(supplyPoint: ISupplyPoint): void {
    const modalRef = this.modalService.open(SupplyPointDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.supplyPoint = supplyPoint;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateSupplyPoints(data: ISupplyPoint[] | null, headers: HttpHeaders): void {
    const headersLink = headers.get('link');
    this.links = this.parseLinks.parse(headersLink ? headersLink : '');
    if (data) {
      for (let i = 0; i < data.length; i++) {
        this.supplyPoints.push(data[i]);
      }
    }
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="crownApp.supplyPoint.home.title">Supply Points</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-supply-point" [routerLink]="['/supply-point/new']">
            <fa-icon icon="plus"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="crownApp.supplyPoint.home.createLabel">
            Create a new Supply Point
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'crownApp.supplyPoint.home.search' | translate }}">

                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon icon="search"></fa-icon>
                    </button>

                    <button class="input-group-append btn btn-danger" (click)="search('')" *ngIf="currentSearch">
                        <fa-icon icon="trash-alt"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="alert alert-warning" id="no-result" *ngIf="supplyPoints?.length === 0">
        <span jhiTranslate="crownApp.supplyPoint.home.notFound">No supplyPoints found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="supplyPoints?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="name"><span jhiTranslate="crownApp.supplyPoint.name">Name</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="address"><span jhiTranslate="crownApp.supplyPoint.address">Address</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="primaryContactName"><span jhiTranslate="crownApp.supplyPoint.primaryContactName">Primary Contact Name</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="zip"><span jhiTranslate="crownApp.supplyPoint.zip">Zip</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="phonenumber"><span jhiTranslate="crownApp.supplyPoint.phonenumber">Phonenumber</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="latx"><span jhiTranslate="crownApp.supplyPoint.latx">Latx</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="longy"><span jhiTranslate="crownApp.supplyPoint.longy">Longy</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="city"><span jhiTranslate="crownApp.supplyPoint.city">City</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="state"><span jhiTranslate="crownApp.supplyPoint.state">State</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="isDistributor"><span jhiTranslate="crownApp.supplyPoint.isDistributor">Is Distributor</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="isHealthcare"><span jhiTranslate="crownApp.supplyPoint.isHealthcare">Is Healthcare</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="hasSterilization"><span jhiTranslate="crownApp.supplyPoint.hasSterilization">Has Sterilization</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="priority"><span jhiTranslate="crownApp.supplyPoint.priority">Priority</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="notes"><span jhiTranslate="crownApp.supplyPoint.notes">Notes</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
                <tr *ngFor="let supplyPoint of supplyPoints ;trackBy: trackId">
                    <td><a [routerLink]="['/supply-point', supplyPoint.id, 'view']">{{ supplyPoint.id }}</a></td>
                    <td>{{ supplyPoint.name }}</td>
                    <td>{{ supplyPoint.address }}</td>
                    <td>{{ supplyPoint.primaryContactName }}</td>
                    <td>{{ supplyPoint.zip }}</td>
                    <td>{{ supplyPoint.phonenumber }}</td>
                    <td>{{ supplyPoint.latx }}</td>
                    <td>{{ supplyPoint.longy }}</td>
                    <td>{{ supplyPoint.city }}</td>
                    <td>{{ supplyPoint.state }}</td>
                    <td>{{ supplyPoint.isDistributor }}</td>
                    <td>{{ supplyPoint.isHealthcare }}</td>
                    <td>{{ supplyPoint.hasSterilization }}</td>
                    <td>{{ supplyPoint.priority }}</td>
                    <td>{{ supplyPoint.notes }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/supply-point', supplyPoint.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/supply-point', supplyPoint.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(supplyPoint)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
