// src/main/webapp/app/entities/supply-point/supply-point-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISupplyPoint } from 'app/shared/model/supply-point.model';

@Component({
  selector: 'jhi-supply-point-detail',
  templateUrl: './supply-point-detail.component.html'
})
export class SupplyPointDetailComponent implements OnInit {
  supplyPoint: ISupplyPoint | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ supplyPoint }) => (this.supplyPoint = supplyPoint));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="supplyPoint">
            <h2><span jhiTranslate="crownApp.supplyPoint.detail.title">Supply Point</span> {{ supplyPoint.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="crownApp.supplyPoint.name">Name</span></dt>
                <dd>
                    <span>{{ supplyPoint.name }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.address">Address</span></dt>
                <dd>
                    <span>{{ supplyPoint.address }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.primaryContactName">Primary Contact Name</span></dt>
                <dd>
                    <span>{{ supplyPoint.primaryContactName }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.zip">Zip</span></dt>
                <dd>
                    <span>{{ supplyPoint.zip }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.phonenumber">Phonenumber</span></dt>
                <dd>
                    <span>{{ supplyPoint.phonenumber }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.latx">Latx</span></dt>
                <dd>
                    <span>{{ supplyPoint.latx }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.longy">Longy</span></dt>
                <dd>
                    <span>{{ supplyPoint.longy }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.city">City</span></dt>
                <dd>
                    <span>{{ supplyPoint.city }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.state">State</span></dt>
                <dd>
                    <span>{{ supplyPoint.state }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.isDistributor">Is Distributor</span></dt>
                <dd>
                    <span>{{ supplyPoint.isDistributor }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.isHealthcare">Is Healthcare</span></dt>
                <dd>
                    <span>{{ supplyPoint.isHealthcare }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.hasSterilization">Has Sterilization</span></dt>
                <dd>
                    <span>{{ supplyPoint.hasSterilization }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.priority">Priority</span></dt>
                <dd>
                    <span>{{ supplyPoint.priority }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPoint.notes">Notes</span></dt>
                <dd>
                    <span>{{ supplyPoint.notes }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/supply-point', supplyPoint.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/supply-point/supply-point-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './supply-point.reducer';
import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISupplyPointDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SupplyPointDetail = (props: ISupplyPointDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { supplyPointEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          <Translate contentKey="crownApp.supplyPoint.detail.title">SupplyPoint</Translate> [<b>{supplyPointEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="name">
              <Translate contentKey="crownApp.supplyPoint.name">Name</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.name}</dd>
          <dt>
            <span id="address">
              <Translate contentKey="crownApp.supplyPoint.address">Address</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.address}</dd>
          <dt>
            <span id="primaryContactName">
              <Translate contentKey="crownApp.supplyPoint.primaryContactName">Primary Contact Name</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.primaryContactName}</dd>
          <dt>
            <span id="zip">
              <Translate contentKey="crownApp.supplyPoint.zip">Zip</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.zip}</dd>
          <dt>
            <span id="phonenumber">
              <Translate contentKey="crownApp.supplyPoint.phonenumber">Phonenumber</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.phonenumber}</dd>
          <dt>
            <span id="latx">
              <Translate contentKey="crownApp.supplyPoint.latx">Latx</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.latx}</dd>
          <dt>
            <span id="longy">
              <Translate contentKey="crownApp.supplyPoint.longy">Longy</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.longy}</dd>
          <dt>
            <span id="city">
              <Translate contentKey="crownApp.supplyPoint.city">City</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.city}</dd>
          <dt>
            <span id="state">
              <Translate contentKey="crownApp.supplyPoint.state">State</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.state}</dd>
          <dt>
            <span id="isDistributor">
              <Translate contentKey="crownApp.supplyPoint.isDistributor">Is Distributor</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.isDistributor ? 'true' : 'false'}</dd>
          <dt>
            <span id="isHealthcare">
              <Translate contentKey="crownApp.supplyPoint.isHealthcare">Is Healthcare</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.isHealthcare ? 'true' : 'false'}</dd>
          <dt>
            <span id="hasSterilization">
              <Translate contentKey="crownApp.supplyPoint.hasSterilization">Has Sterilization</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.hasSterilization ? 'true' : 'false'}</dd>
          <dt>
            <span id="priority">
              <Translate contentKey="crownApp.supplyPoint.priority">Priority</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.priority}</dd>
          <dt>
            <span id="notes">
              <Translate contentKey="crownApp.supplyPoint.notes">Notes</Translate>
            </span>
          </dt>
          <dd>{supplyPointEntity.notes}</dd>
        </dl>
        <Button tag={Link} to="/supply-point" replace color="info">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/supply-point/${supplyPointEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ supplyPoint }: IRootState) => ({
  supplyPointEntity: supplyPoint.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPointDetail);
