// src/main/webapp/app/entities/supply-point/supply-point-delete-dialog.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate, ICrudGetAction, ICrudDeleteAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { IRootState } from 'app/shared/reducers';
import { getEntity, deleteEntity } from './supply-point.reducer';

export interface ISupplyPointDeleteDialogProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SupplyPointDeleteDialog = (props: ISupplyPointDeleteDialogProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const handleClose = () => {
    props.history.push('/supply-point');
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const confirmDelete = () => {
    props.deleteEntity(props.supplyPointEntity.id);
  };

  const { supplyPointEntity } = props;
  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose}>
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="crownApp.supplyPoint.delete.question">
        <Translate contentKey="crownApp.supplyPoint.delete.question" interpolate={{ id: supplyPointEntity.id }}>
          Are you sure you want to delete this SupplyPoint?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-supplyPoint" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

const mapStateToProps = ({ supplyPoint }: IRootState) => ({
  supplyPointEntity: supplyPoint.entity,
  updateSuccess: supplyPoint.updateSuccess
});

const mapDispatchToProps = { getEntity, deleteEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPointDeleteDialog);

// src/main/webapp/app/entities/supply-point/supply-point-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { JhiEventManager } from 'ng-jhipster';

import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { SupplyPointService } from './supply-point.service';

@Component({
  templateUrl: './supply-point-delete-dialog.component.html'
})
export class SupplyPointDeleteDialogComponent {
  supplyPoint?: ISupplyPoint;

  constructor(
    protected supplyPointService: SupplyPointService,
    public activeModal: NgbActiveModal,
    protected eventManager: JhiEventManager
  ) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: string): void {
    this.supplyPointService.delete(id).subscribe(() => {
      this.eventManager.broadcast('supplyPointListModification');
      this.activeModal.close();
    });
  }
}

<form *ngIf="supplyPoint" name="deleteForm" (ngSubmit)="confirmDelete(supplyPoint?.id!)">
    <div class="modal-header">
        <h4 class="modal-title" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
                (click)="cancel()">&times;</button>
    </div>

    <div class="modal-body">
        <jhi-alert-error></jhi-alert-error>

        <p id="jhi-delete-supplyPoint-heading" jhiTranslate="crownApp.supplyPoint.delete.question" [translateValues]="{ id: supplyPoint.id }">Are you sure you want to delete this Supply Point?</p>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
            <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button id="jhi-confirm-delete-supplyPoint" type="submit" class="btn btn-danger">
            <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
        </button>
    </div>
</form>
