// src/main/webapp/app/entities/supply-point/supply-point-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './supply-point.reducer';
import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ISupplyPointUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SupplyPointUpdate = (props: ISupplyPointUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { supplyPointEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/supply-point');
  };

  useEffect(() => {
    if (!isNew) {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...supplyPointEntity,
        ...values
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="crownApp.supplyPoint.home.createOrEditLabel">
            <Translate contentKey="crownApp.supplyPoint.home.createOrEditLabel">Create or edit a SupplyPoint</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : supplyPointEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="supply-point-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="supply-point-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nameLabel" for="supply-point-name">
                  <Translate contentKey="crownApp.supplyPoint.name">Name</Translate>
                </Label>
                <AvField
                  id="supply-point-name"
                  type="text"
                  name="name"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') }
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="addressLabel" for="supply-point-address">
                  <Translate contentKey="crownApp.supplyPoint.address">Address</Translate>
                </Label>
                <AvField id="supply-point-address" type="text" name="address" />
              </AvGroup>
              <AvGroup>
                <Label id="primaryContactNameLabel" for="supply-point-primaryContactName">
                  <Translate contentKey="crownApp.supplyPoint.primaryContactName">Primary Contact Name</Translate>
                </Label>
                <AvField
                  id="supply-point-primaryContactName"
                  type="text"
                  name="primaryContactName"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') }
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="zipLabel" for="supply-point-zip">
                  <Translate contentKey="crownApp.supplyPoint.zip">Zip</Translate>
                </Label>
                <AvField
                  id="supply-point-zip"
                  type="text"
                  name="zip"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') }
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="phonenumberLabel" for="supply-point-phonenumber">
                  <Translate contentKey="crownApp.supplyPoint.phonenumber">Phonenumber</Translate>
                </Label>
                <AvField id="supply-point-phonenumber" type="text" name="phonenumber" />
              </AvGroup>
              <AvGroup>
                <Label id="latxLabel" for="supply-point-latx">
                  <Translate contentKey="crownApp.supplyPoint.latx">Latx</Translate>
                </Label>
                <AvField id="supply-point-latx" type="string" className="form-control" name="latx" />
              </AvGroup>
              <AvGroup>
                <Label id="longyLabel" for="supply-point-longy">
                  <Translate contentKey="crownApp.supplyPoint.longy">Longy</Translate>
                </Label>
                <AvField id="supply-point-longy" type="string" className="form-control" name="longy" />
              </AvGroup>
              <AvGroup>
                <Label id="cityLabel" for="supply-point-city">
                  <Translate contentKey="crownApp.supplyPoint.city">City</Translate>
                </Label>
                <AvField id="supply-point-city" type="text" name="city" />
              </AvGroup>
              <AvGroup>
                <Label id="stateLabel" for="supply-point-state">
                  <Translate contentKey="crownApp.supplyPoint.state">State</Translate>
                </Label>
                <AvField id="supply-point-state" type="text" name="state" />
              </AvGroup>
              <AvGroup check>
                <Label id="isDistributorLabel">
                  <AvInput id="supply-point-isDistributor" type="checkbox" className="form-check-input" name="isDistributor" />
                  <Translate contentKey="crownApp.supplyPoint.isDistributor">Is Distributor</Translate>
                </Label>
              </AvGroup>
              <AvGroup check>
                <Label id="isHealthcareLabel">
                  <AvInput id="supply-point-isHealthcare" type="checkbox" className="form-check-input" name="isHealthcare" />
                  <Translate contentKey="crownApp.supplyPoint.isHealthcare">Is Healthcare</Translate>
                </Label>
              </AvGroup>
              <AvGroup check>
                <Label id="hasSterilizationLabel">
                  <AvInput id="supply-point-hasSterilization" type="checkbox" className="form-check-input" name="hasSterilization" />
                  <Translate contentKey="crownApp.supplyPoint.hasSterilization">Has Sterilization</Translate>
                </Label>
              </AvGroup>
              <AvGroup>
                <Label id="priorityLabel" for="supply-point-priority">
                  <Translate contentKey="crownApp.supplyPoint.priority">Priority</Translate>
                </Label>
                <AvField id="supply-point-priority" type="string" className="form-control" name="priority" />
              </AvGroup>
              <AvGroup>
                <Label id="notesLabel" for="supply-point-notes">
                  <Translate contentKey="crownApp.supplyPoint.notes">Notes</Translate>
                </Label>
                <AvField id="supply-point-notes" type="text" name="notes" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/supply-point" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  supplyPointEntity: storeState.supplyPoint.entity,
  loading: storeState.supplyPoint.loading,
  updating: storeState.supplyPoint.updating,
  updateSuccess: storeState.supplyPoint.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPointUpdate);

// src/main/webapp/app/entities/supply-point/supply-point-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ISupplyPoint, SupplyPoint } from 'app/shared/model/supply-point.model';
import { SupplyPointService } from './supply-point.service';

@Component({
  selector: 'jhi-supply-point-update',
  templateUrl: './supply-point-update.component.html'
})
export class SupplyPointUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    address: [],
    primaryContactName: [null, [Validators.required]],
    zip: [null, [Validators.required]],
    phonenumber: [],
    latx: [],
    longy: [],
    city: [],
    state: [],
    isDistributor: [],
    isHealthcare: [],
    hasSterilization: [],
    priority: [],
    notes: []
  });

  constructor(protected supplyPointService: SupplyPointService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ supplyPoint }) => {
      this.updateForm(supplyPoint);
    });
  }

  updateForm(supplyPoint: ISupplyPoint): void {
    this.editForm.patchValue({
      id: supplyPoint.id,
      name: supplyPoint.name,
      address: supplyPoint.address,
      primaryContactName: supplyPoint.primaryContactName,
      zip: supplyPoint.zip,
      phonenumber: supplyPoint.phonenumber,
      latx: supplyPoint.latx,
      longy: supplyPoint.longy,
      city: supplyPoint.city,
      state: supplyPoint.state,
      isDistributor: supplyPoint.isDistributor,
      isHealthcare: supplyPoint.isHealthcare,
      hasSterilization: supplyPoint.hasSterilization,
      priority: supplyPoint.priority,
      notes: supplyPoint.notes
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const supplyPoint = this.createFromForm();
    if (supplyPoint.id !== undefined) {
      this.subscribeToSaveResponse(this.supplyPointService.update(supplyPoint));
    } else {
      this.subscribeToSaveResponse(this.supplyPointService.create(supplyPoint));
    }
  }

  private createFromForm(): ISupplyPoint {
    return {
      ...new SupplyPoint(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      address: this.editForm.get(['address'])!.value,
      primaryContactName: this.editForm.get(['primaryContactName'])!.value,
      zip: this.editForm.get(['zip'])!.value,
      phonenumber: this.editForm.get(['phonenumber'])!.value,
      latx: this.editForm.get(['latx'])!.value,
      longy: this.editForm.get(['longy'])!.value,
      city: this.editForm.get(['city'])!.value,
      state: this.editForm.get(['state'])!.value,
      isDistributor: this.editForm.get(['isDistributor'])!.value,
      isHealthcare: this.editForm.get(['isHealthcare'])!.value,
      hasSterilization: this.editForm.get(['hasSterilization'])!.value,
      priority: this.editForm.get(['priority'])!.value,
      notes: this.editForm.get(['notes'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISupplyPoint>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-supply-point-heading" jhiTranslate="crownApp.supplyPoint.home.createOrEditLabel">Create or edit a Supply Point</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                    <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.address" for="field_address">Address</label>
                    <input type="text" class="form-control" name="address" id="field_address"
                           formControlName="address"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.primaryContactName" for="field_primaryContactName">Primary Contact Name</label>
                    <input type="text" class="form-control" name="primaryContactName" id="field_primaryContactName"
                           formControlName="primaryContactName"/>
                    <div *ngIf="editForm.get('primaryContactName')!.invalid && (editForm.get('primaryContactName')!.dirty || editForm.get('primaryContactName')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('primaryContactName')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.zip" for="field_zip">Zip</label>
                    <input type="text" class="form-control" name="zip" id="field_zip"
                           formControlName="zip"/>
                    <div *ngIf="editForm.get('zip')!.invalid && (editForm.get('zip')!.dirty || editForm.get('zip')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('zip')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.phonenumber" for="field_phonenumber">Phonenumber</label>
                    <input type="text" class="form-control" name="phonenumber" id="field_phonenumber"
                           formControlName="phonenumber"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.latx" for="field_latx">Latx</label>
                    <input type="number" class="form-control" name="latx" id="field_latx"
                           formControlName="latx"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.longy" for="field_longy">Longy</label>
                    <input type="number" class="form-control" name="longy" id="field_longy"
                           formControlName="longy"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.city" for="field_city">City</label>
                    <input type="text" class="form-control" name="city" id="field_city"
                           formControlName="city"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.state" for="field_state">State</label>
                    <input type="text" class="form-control" name="state" id="field_state"
                           formControlName="state"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.isDistributor" for="field_isDistributor">Is Distributor</label>
                    <input type="checkbox" class="form-control" name="isDistributor" id="field_isDistributor"
                           formControlName="isDistributor"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.isHealthcare" for="field_isHealthcare">Is Healthcare</label>
                    <input type="checkbox" class="form-control" name="isHealthcare" id="field_isHealthcare"
                           formControlName="isHealthcare"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.hasSterilization" for="field_hasSterilization">Has Sterilization</label>
                    <input type="checkbox" class="form-control" name="hasSterilization" id="field_hasSterilization"
                           formControlName="hasSterilization"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.priority" for="field_priority">Priority</label>
                    <input type="number" class="form-control" name="priority" id="field_priority"
                           formControlName="priority"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPoint.notes" for="field_notes">Notes</label>
                    <input type="text" class="form-control" name="notes" id="field_notes"
                           formControlName="notes"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
