// src/main/webapp/app/entities/resource/resource-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IResource } from 'app/shared/model/resource.model';

@Component({
  selector: 'jhi-resource-detail',
  templateUrl: './resource-detail.component.html'
})
export class ResourceDetailComponent implements OnInit {
  resource: IResource | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ resource }) => (this.resource = resource));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="resource">
            <h2><span jhiTranslate="crownApp.resource.detail.title">Resource</span> {{ resource.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="crownApp.resource.name">Name</span></dt>
                <dd>
                    <span>{{ resource.name }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.resource.notes">Notes</span></dt>
                <dd>
                    <span>{{ resource.notes }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.resource.supplyPointResource">Supply Point Resource</span></dt>
                <dd>
                    <div *ngIf="resource.supplyPointResource">
                        <a [routerLink]="['/supply-point-resource', resource.supplyPointResource?.id, 'view']">{{ resource.supplyPointResource?.id }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/resource', resource.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/resource/resource-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './resource.reducer';
import { IResource } from 'app/shared/model/resource.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IResourceDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ResourceDetail = (props: IResourceDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { resourceEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          <Translate contentKey="crownApp.resource.detail.title">Resource</Translate> [<b>{resourceEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="name">
              <Translate contentKey="crownApp.resource.name">Name</Translate>
            </span>
          </dt>
          <dd>{resourceEntity.name}</dd>
          <dt>
            <span id="notes">
              <Translate contentKey="crownApp.resource.notes">Notes</Translate>
            </span>
          </dt>
          <dd>{resourceEntity.notes}</dd>
          <dt>
            <Translate contentKey="crownApp.resource.supplyPointResource">Supply Point Resource</Translate>
          </dt>
          <dd>{resourceEntity.supplyPointResource ? resourceEntity.supplyPointResource.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/resource" replace color="info">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/resource/${resourceEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ resource }: IRootState) => ({
  resourceEntity: resource.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ResourceDetail);
