// src/main/webapp/app/entities/supply-point-resource/supply-point-resource-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISupplyPointResource } from 'app/shared/model/supply-point-resource.model';

@Component({
  selector: 'jhi-supply-point-resource-detail',
  templateUrl: './supply-point-resource-detail.component.html'
})
export class SupplyPointResourceDetailComponent implements OnInit {
  supplyPointResource: ISupplyPointResource | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ supplyPointResource }) => (this.supplyPointResource = supplyPointResource));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="supplyPointResource">
            <h2><span jhiTranslate="crownApp.supplyPointResource.detail.title">Supply Point Resource</span> {{ supplyPointResource.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="crownApp.supplyPointResource.numRequested">Num Requested</span></dt>
                <dd>
                    <span>{{ supplyPointResource.numRequested }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPointResource.canProduce">Can Produce</span></dt>
                <dd>
                    <span>{{ supplyPointResource.canProduce }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPointResource.numinStock">Numin Stock</span></dt>
                <dd>
                    <span>{{ supplyPointResource.numinStock }}</span>
                </dd>
                <dt><span jhiTranslate="crownApp.supplyPointResource.supplyPoint">Supply Point</span></dt>
                <dd>
                    <div *ngIf="supplyPointResource.supplyPoint">
                        <a [routerLink]="['/supply-point', supplyPointResource.supplyPoint?.id, 'view']">{{ supplyPointResource.supplyPoint?.id }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/supply-point-resource', supplyPointResource.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/supply-point-resource/supply-point-resource-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './supply-point-resource.reducer';
import { ISupplyPointResource } from 'app/shared/model/supply-point-resource.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISupplyPointResourceDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SupplyPointResourceDetail = (props: ISupplyPointResourceDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { supplyPointResourceEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          <Translate contentKey="crownApp.supplyPointResource.detail.title">SupplyPointResource</Translate> [
          <b>{supplyPointResourceEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="numRequested">
              <Translate contentKey="crownApp.supplyPointResource.numRequested">Num Requested</Translate>
            </span>
          </dt>
          <dd>{supplyPointResourceEntity.numRequested}</dd>
          <dt>
            <span id="canProduce">
              <Translate contentKey="crownApp.supplyPointResource.canProduce">Can Produce</Translate>
            </span>
          </dt>
          <dd>{supplyPointResourceEntity.canProduce}</dd>
          <dt>
            <span id="numinStock">
              <Translate contentKey="crownApp.supplyPointResource.numinStock">Numin Stock</Translate>
            </span>
          </dt>
          <dd>{supplyPointResourceEntity.numinStock}</dd>
          <dt>
            <Translate contentKey="crownApp.supplyPointResource.supplypoint">Supplypoint</Translate>
          </dt>
          <dd>{supplyPointResourceEntity.supplypoint ? supplyPointResourceEntity.supplypoint.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/supply-point-resource" replace color="info">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/supply-point-resource/${supplyPointResourceEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ supplyPointResource }: IRootState) => ({
  supplyPointResourceEntity: supplyPointResource.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPointResourceDetail);
