// src/main/webapp/app/entities/supply-point-resource/supply-point-resource-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ISupplyPointResource, SupplyPointResource } from 'app/shared/model/supply-point-resource.model';
import { SupplyPointResourceService } from './supply-point-resource.service';
import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { SupplyPointService } from 'app/entities/supply-point/supply-point.service';

@Component({
  selector: 'jhi-supply-point-resource-update',
  templateUrl: './supply-point-resource-update.component.html'
})
export class SupplyPointResourceUpdateComponent implements OnInit {
  isSaving = false;
  supplypoints: ISupplyPoint[] = [];

  editForm = this.fb.group({
    id: [],
    numRequested: [],
    canProduce: [],
    numinStock: [],
    supplyPoint: []
  });

  constructor(
    protected supplyPointResourceService: SupplyPointResourceService,
    protected supplyPointService: SupplyPointService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ supplyPointResource }) => {
      this.updateForm(supplyPointResource);

      this.supplyPointService.query().subscribe((res: HttpResponse<ISupplyPoint[]>) => (this.supplypoints = res.body || []));
    });
  }

  updateForm(supplyPointResource: ISupplyPointResource): void {
    this.editForm.patchValue({
      id: supplyPointResource.id,
      numRequested: supplyPointResource.numRequested,
      canProduce: supplyPointResource.canProduce,
      numinStock: supplyPointResource.numinStock,
      supplyPoint: supplyPointResource.supplyPoint
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const supplyPointResource = this.createFromForm();
    if (supplyPointResource.id !== undefined) {
      this.subscribeToSaveResponse(this.supplyPointResourceService.update(supplyPointResource));
    } else {
      this.subscribeToSaveResponse(this.supplyPointResourceService.create(supplyPointResource));
    }
  }

  private createFromForm(): ISupplyPointResource {
    return {
      ...new SupplyPointResource(),
      id: this.editForm.get(['id'])!.value,
      numRequested: this.editForm.get(['numRequested'])!.value,
      canProduce: this.editForm.get(['canProduce'])!.value,
      numinStock: this.editForm.get(['numinStock'])!.value,
      supplyPoint: this.editForm.get(['supplyPoint'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISupplyPointResource>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: ISupplyPoint): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-supply-point-resource-heading" jhiTranslate="crownApp.supplyPointResource.home.createOrEditLabel">Create or edit a Supply Point Resource</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPointResource.numRequested" for="field_numRequested">Num Requested</label>
                    <input type="number" class="form-control" name="numRequested" id="field_numRequested"
                           formControlName="numRequested"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPointResource.canProduce" for="field_canProduce">Can Produce</label>
                    <input type="number" class="form-control" name="canProduce" id="field_canProduce"
                           formControlName="canProduce"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPointResource.numinStock" for="field_numinStock">Numin Stock</label>
                    <input type="number" class="form-control" name="numinStock" id="field_numinStock"
                           formControlName="numinStock"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="crownApp.supplyPointResource.supplyPoint" for="field_supplyPoint">Supply Point</label>
                    <select class="form-control" id="field_supplyPoint" name="supplyPoint" formControlName="supplyPoint">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="supplyPointOption.id === editForm.get('supplyPoint')!.value?.id ? editForm.get('supplyPoint')!.value : supplyPointOption" *ngFor="let supplyPointOption of supplypoints; trackBy: trackById">{{ supplyPointOption.id }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/supply-point-resource/supply-point-resource-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ISupplyPoint } from 'app/shared/model/supply-point.model';
import { getEntities as getSupplyPoints } from 'app/entities/supply-point/supply-point.reducer';
import { getEntity, updateEntity, createEntity, reset } from './supply-point-resource.reducer';
import { ISupplyPointResource } from 'app/shared/model/supply-point-resource.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ISupplyPointResourceUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SupplyPointResourceUpdate = (props: ISupplyPointResourceUpdateProps) => {
  const [supplypointId, setSupplypointId] = useState('0');
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { supplyPointResourceEntity, supplyPoints, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/supply-point-resource');
  };

  useEffect(() => {
    if (!isNew) {
      props.getEntity(props.match.params.id);
    }

    props.getSupplyPoints();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...supplyPointResourceEntity,
        ...values
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="crownApp.supplyPointResource.home.createOrEditLabel">
            <Translate contentKey="crownApp.supplyPointResource.home.createOrEditLabel">Create or edit a SupplyPointResource</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : supplyPointResourceEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="supply-point-resource-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="supply-point-resource-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="numRequestedLabel" for="supply-point-resource-numRequested">
                  <Translate contentKey="crownApp.supplyPointResource.numRequested">Num Requested</Translate>
                </Label>
                <AvField id="supply-point-resource-numRequested" type="string" className="form-control" name="numRequested" />
              </AvGroup>
              <AvGroup>
                <Label id="canProduceLabel" for="supply-point-resource-canProduce">
                  <Translate contentKey="crownApp.supplyPointResource.canProduce">Can Produce</Translate>
                </Label>
                <AvField id="supply-point-resource-canProduce" type="string" className="form-control" name="canProduce" />
              </AvGroup>
              <AvGroup>
                <Label id="numinStockLabel" for="supply-point-resource-numinStock">
                  <Translate contentKey="crownApp.supplyPointResource.numinStock">Numin Stock</Translate>
                </Label>
                <AvField id="supply-point-resource-numinStock" type="string" className="form-control" name="numinStock" />
              </AvGroup>
              <AvGroup>
                <Label for="supply-point-resource-supplypoint">
                  <Translate contentKey="crownApp.supplyPointResource.supplypoint">Supplypoint</Translate>
                </Label>
                <AvInput id="supply-point-resource-supplypoint" type="select" className="form-control" name="supplypoint.id">
                  <option value="" key="0" />
                  {supplyPoints
                    ? supplyPoints.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/supply-point-resource" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  supplyPoints: storeState.supplyPoint.entities,
  supplyPointResourceEntity: storeState.supplyPointResource.entity,
  loading: storeState.supplyPointResource.loading,
  updating: storeState.supplyPointResource.updating,
  updateSuccess: storeState.supplyPointResource.updateSuccess
});

const mapDispatchToProps = {
  getSupplyPoints,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPointResourceUpdate);
