// src/main/webapp/app/entities/supply-point-resource/supply-point-resource.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiParseLinks } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ISupplyPointResource } from 'app/shared/model/supply-point-resource.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { SupplyPointResourceService } from './supply-point-resource.service';
import { SupplyPointResourceDeleteDialogComponent } from './supply-point-resource-delete-dialog.component';

@Component({
  selector: 'jhi-supply-point-resource',
  templateUrl: './supply-point-resource.component.html'
})
export class SupplyPointResourceComponent implements OnInit, OnDestroy {
  supplyPointResources: ISupplyPointResource[];
  eventSubscriber?: Subscription;
  itemsPerPage: number;
  links: any;
  page: number;
  predicate: string;
  ascending: boolean;
  currentSearch: string;

  constructor(
    protected supplyPointResourceService: SupplyPointResourceService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal,
    protected parseLinks: JhiParseLinks,
    protected activatedRoute: ActivatedRoute
  ) {
    this.supplyPointResources = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0
    };
    this.predicate = 'id';
    this.ascending = true;
    this.currentSearch =
      this.activatedRoute.snapshot && this.activatedRoute.snapshot.queryParams['search']
        ? this.activatedRoute.snapshot.queryParams['search']
        : '';
  }

  loadAll(): void {
    if (this.currentSearch) {
      this.supplyPointResourceService
        .search({
          query: this.currentSearch,
          page: this.page,
          size: this.itemsPerPage,
          sort: this.sort()
        })
        .subscribe((res: HttpResponse<ISupplyPointResource[]>) => this.paginateSupplyPointResources(res.body, res.headers));
      return;
    }

    this.supplyPointResourceService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe((res: HttpResponse<ISupplyPointResource[]>) => this.paginateSupplyPointResources(res.body, res.headers));
  }

  reset(): void {
    this.page = 0;
    this.supplyPointResources = [];
    this.loadAll();
  }

  loadPage(page: number): void {
    this.page = page;
    this.loadAll();
  }

  search(query: string): void {
    this.supplyPointResources = [];
    this.links = {
      last: 0
    };
    this.page = 0;
    if (query) {
      this.predicate = '_score';
      this.ascending = false;
    } else {
      this.predicate = 'id';
      this.ascending = true;
    }
    this.currentSearch = query;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInSupplyPointResources();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: ISupplyPointResource): string {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInSupplyPointResources(): void {
    this.eventSubscriber = this.eventManager.subscribe('supplyPointResourceListModification', () => this.reset());
  }

  delete(supplyPointResource: ISupplyPointResource): void {
    const modalRef = this.modalService.open(SupplyPointResourceDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.supplyPointResource = supplyPointResource;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateSupplyPointResources(data: ISupplyPointResource[] | null, headers: HttpHeaders): void {
    const headersLink = headers.get('link');
    this.links = this.parseLinks.parse(headersLink ? headersLink : '');
    if (data) {
      for (let i = 0; i < data.length; i++) {
        this.supplyPointResources.push(data[i]);
      }
    }
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="crownApp.supplyPointResource.home.title">Supply Point Resources</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-supply-point-resource" [routerLink]="['/supply-point-resource/new']">
            <fa-icon icon="plus"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="crownApp.supplyPointResource.home.createLabel">
            Create a new Supply Point Resource
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'crownApp.supplyPointResource.home.search' | translate }}">

                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon icon="search"></fa-icon>
                    </button>

                    <button class="input-group-append btn btn-danger" (click)="search('')" *ngIf="currentSearch">
                        <fa-icon icon="trash-alt"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="alert alert-warning" id="no-result" *ngIf="supplyPointResources?.length === 0">
        <span jhiTranslate="crownApp.supplyPointResource.home.notFound">No supplyPointResources found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="supplyPointResources?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="numRequested"><span jhiTranslate="crownApp.supplyPointResource.numRequested">Num Requested</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="canProduce"><span jhiTranslate="crownApp.supplyPointResource.canProduce">Can Produce</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="numinStock"><span jhiTranslate="crownApp.supplyPointResource.numinStock">Numin Stock</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="supplyPoint.id"><span jhiTranslate="crownApp.supplyPointResource.supplyPoint">Supply Point</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
                <tr *ngFor="let supplyPointResource of supplyPointResources ;trackBy: trackId">
                    <td><a [routerLink]="['/supply-point-resource', supplyPointResource.id, 'view']">{{ supplyPointResource.id }}</a></td>
                    <td>{{ supplyPointResource.numRequested }}</td>
                    <td>{{ supplyPointResource.canProduce }}</td>
                    <td>{{ supplyPointResource.numinStock }}</td>
                    <td>
                        <div *ngIf="supplyPointResource.supplyPoint">
                            <a [routerLink]="['/supply-point', supplyPointResource.supplyPoint?.id, 'view']" >{{ supplyPointResource.supplyPoint?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/supply-point-resource', supplyPointResource.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/supply-point-resource', supplyPointResource.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(supplyPointResource)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/supply-point-resource/supply-point-resource.tsx
import React, { useState, useEffect } from 'react';
import InfiniteScroll from 'react-infinite-scroller';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, getSortState, IPaginationBaseState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities, reset } from './supply-point-resource.reducer';
import { ISupplyPointResource } from 'app/shared/model/supply-point-resource.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface ISupplyPointResourceProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const SupplyPointResource = (props: ISupplyPointResourceProps) => {
  const [search, setSearch] = useState('');
  const [paginationState, setPaginationState] = useState(getSortState(props.location, ITEMS_PER_PAGE));
  const [sorting, setSorting] = useState(false);

  const getAllEntities = () => {
    if (search) {
      props.getSearchEntities(
        search,
        paginationState.activePage - 1,
        paginationState.itemsPerPage,
        `${paginationState.sort},${paginationState.order}`
      );
    } else {
      props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
    }
  };

  const resetAll = () => {
    props.reset();
    setPaginationState({
      ...paginationState,
      activePage: 1
    });
  };

  useEffect(() => {
    resetAll();
  }, []);

  const startSearching = () => {
    if (search) {
      props.reset();
      setPaginationState({
        ...paginationState,
        activePage: 1
      });
      props.getSearchEntities(
        search,
        paginationState.activePage - 1,
        paginationState.itemsPerPage,
        `${paginationState.sort},${paginationState.order}`
      );
    }
  };

  const clear = () => {
    props.reset();
    setSearch('');
    setPaginationState({
      ...paginationState,
      activePage: 1
    });
    props.getEntities();
  };

  const handleSearch = event => setSearch(event.target.value);

  useEffect(() => {
    getAllEntities();
  }, [paginationState.activePage]);

  const handleLoadMore = () => {
    if (window.pageYOffset > 0) {
      setPaginationState({
        ...paginationState,
        activePage: paginationState.activePage + 1
      });
    }
  };

  useEffect(() => {
    if (sorting) {
      getAllEntities();
      setSorting(false);
    }
  }, [sorting, search]);

  const sort = p => () => {
    props.reset();
    setPaginationState({
      ...paginationState,
      activePage: 1,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p
    });
    setSorting(true);
  };

  const { supplyPointResourceList, match, loading } = props;
  return (
    <div>
      <h2 id="supply-point-resource-heading">
        <Translate contentKey="crownApp.supplyPointResource.home.title">Supply Point Resources</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="crownApp.supplyPointResource.home.createLabel">Create new Supply Point Resource</Translate>
        </Link>
      </h2>
      <Row>
        <Col sm="12">
          <AvForm onSubmit={startSearching}>
            <AvGroup>
              <InputGroup>
                <AvInput
                  type="text"
                  name="search"
                  value={search}
                  onChange={handleSearch}
                  placeholder={translate('crownApp.supplyPointResource.home.search')}
                />
                <Button className="input-group-addon">
                  <FontAwesomeIcon icon="search" />
                </Button>
                <Button type="reset" className="input-group-addon" onClick={clear}>
                  <FontAwesomeIcon icon="trash" />
                </Button>
              </InputGroup>
            </AvGroup>
          </AvForm>
        </Col>
      </Row>
      <div className="table-responsive">
        <InfiniteScroll
          pageStart={paginationState.activePage}
          loadMore={handleLoadMore}
          hasMore={paginationState.activePage - 1 < props.links.next}
          loader={<div className="loader">Loading ...</div>}
          threshold={0}
          initialLoad={false}
        >
          {supplyPointResourceList && supplyPointResourceList.length > 0 ? (
            <Table responsive>
              <thead>
                <tr>
                  <th className="hand" onClick={sort('id')}>
                    <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('numRequested')}>
                    <Translate contentKey="crownApp.supplyPointResource.numRequested">Num Requested</Translate>{' '}
                    <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('canProduce')}>
                    <Translate contentKey="crownApp.supplyPointResource.canProduce">Can Produce</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={sort('numinStock')}>
                    <Translate contentKey="crownApp.supplyPointResource.numinStock">Numin Stock</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th>
                    <Translate contentKey="crownApp.supplyPointResource.supplypoint">Supplypoint</Translate> <FontAwesomeIcon icon="sort" />
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {supplyPointResourceList.map((supplyPointResource, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${supplyPointResource.id}`} color="link" size="sm">
                        {supplyPointResource.id}
                      </Button>
                    </td>
                    <td>{supplyPointResource.numRequested}</td>
                    <td>{supplyPointResource.canProduce}</td>
                    <td>{supplyPointResource.numinStock}</td>
                    <td>
                      {supplyPointResource.supplypoint ? (
                        <Link to={`supply-point/${supplyPointResource.supplypoint.id}`}>{supplyPointResource.supplypoint.id}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${supplyPointResource.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${supplyPointResource.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${supplyPointResource.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            !loading && (
              <div className="alert alert-warning">
                <Translate contentKey="crownApp.supplyPointResource.home.notFound">No Supply Point Resources found</Translate>
              </div>
            )
          )}
        </InfiniteScroll>
      </div>
    </div>
  );
};

const mapStateToProps = ({ supplyPointResource }: IRootState) => ({
  supplyPointResourceList: supplyPointResource.entities,
  loading: supplyPointResource.loading,
  totalItems: supplyPointResource.totalItems,
  links: supplyPointResource.links,
  entity: supplyPointResource.entity,
  updateSuccess: supplyPointResource.updateSuccess
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SupplyPointResource);
